extends:
  - '@gitlab'
globals:
  __webpack_public_path__: true
  gl: false
  gon: false
  localStorage: false
  IS_EE: false
plugins:
  - import
  - html
  - "@gitlab/i18n"
  - vue-i18n
settings:
  import/resolver:
    webpack:
      config: './config/webpack.config.js'
  vue-i18n:
    localeDir: './app/assets/javascripts/locale/gitlab.pot'      
rules:
  "@gitlab/i18n/no-non-i18n-strings": error
  import/no-commonjs: error
  no-underscore-dangle:
    - error
    - allow:
        - __
        - _links
  # Disabled for now, to make the airbnb-base 12.1.0 -> 13.1.0 update smoother
  no-else-return:
    - error
    - allowElseIf: true
  import/no-useless-path-segments: off
  lines-between-class-members: off
  # Disabled for now, to make the plugin-vue 4.5 -> 5.0 update smoother
  vue/no-confusing-v-for-v-if: error
  vue/no-unused-components: off
  vue/no-use-v-if-with-v-for: off
  vue/no-v-html: off
  vue/use-v-on-exact: off
  # disable additional rules appearing with vue-i18n
  vue/attributes-order: off
  vue/valid-template-root: off
  vue/require-component-is: off  
  vue-i18n/no-missing-keys: error
  vue-i18n/no-dynamic-keys: error
  vue-i18n/no-unused-keys:
    - error
    - extensions: [.vue]
  vue-i18n/no-bare-strings: error  
  vue-i18n/no-bare-attribute-strings: error  
overrides:
  files:
    - '**/spec/**/*'
  rules:
    "@gitlab/i18n/no-non-i18n-strings": off
