#!/bin/sh
declare -a arr=("app/assets/javascripts/badges/components/badge.vue"
"app/assets/javascripts/boards/components/board_blank_state.vue"
"app/assets/javascripts/boards/components/modal/empty_state.vue"
"app/assets/javascripts/boards/components/modal/header.vue"
"app/assets/javascripts/boards/components/project_select.vue"
"app/assets/javascripts/clusters/components/knative_domain_editor.vue"
"app/assets/javascripts/clusters/components/uninstall_application_button.vue"
"app/assets/javascripts/diffs/components/commit_item.vue"
"app/assets/javascripts/environments/components/environment_actions.vue"
"app/assets/javascripts/environments/components/environment_item.vue"
"app/assets/javascripts/environments/components/environment_monitoring.vue"
"app/assets/javascripts/environments/components/environment_terminal_button.vue"
"app/assets/javascripts/ide/components/commit_sidebar/list_item.vue"
"app/assets/javascripts/ide/components/repo_editor.vue"
"app/assets/javascripts/ide/components/repo_file_status_icon.vue"
"app/assets/javascripts/ide/components/repo_tab.vue"
"app/assets/javascripts/jobs/components/job_log_controllers.vue"
"app/assets/javascripts/jobs/components/sidebar.vue"
"app/assets/javascripts/monitoring/components/charts/area.vue"
"app/assets/javascripts/monitoring/components/empty_state.vue"
"app/assets/javascripts/mr_popover/components/mr_popover.vue"
"app/assets/javascripts/notebook/cells/markdown.vue"
"app/assets/javascripts/notebook/cells/output/image.vue"
"app/assets/javascripts/notebook/index.vue"
"app/assets/javascripts/notes/components/note_awards_list.vue"
"app/assets/javascripts/notes/components/noteable_note.vue"
"app/assets/javascripts/notes/components/notes_app.vue"
"app/assets/javascripts/pages/projects/shared/permissions/components/project_feature_setting.vue"
"app/assets/javascripts/pages/projects/shared/permissions/components/settings_panel.vue"
"app/assets/javascripts/performance_bar/components/performance_bar_app.vue"
"app/assets/javascripts/pipelines/components/header_component.vue"
"app/assets/javascripts/projects/tree/components/commit_pipeline_status_component.vue"
"app/assets/javascripts/releases/components/release_block.vue"
"app/assets/javascripts/serverless/components/area.vue"
"app/assets/javascripts/sidebar/components/assignees/assignee_title.vue"
"app/assets/javascripts/sidebar/components/assignees/sidebar_assignees.vue"
"app/assets/javascripts/sidebar/components/confidential/edit_form_buttons.vue"
"app/assets/javascripts/sidebar/components/time_tracking/comparison_pane.vue"
"app/assets/javascripts/vue_merge_request_widget/components/states/mr_widget_auto_merge_enabled.vue"
"app/assets/javascripts/vue_merge_request_widget/components/states/mr_widget_rebase.vue"
"app/assets/javascripts/vue_shared/components/commit.vue"
"app/assets/javascripts/vue_shared/components/deprecated_modal.vue"
"app/assets/javascripts/vue_shared/components/header_ci_component.vue"
"app/assets/javascripts/vue_shared/components/issue/issue_warning.vue"
"app/assets/javascripts/vue_shared/components/markdown/header.vue"
"app/assets/javascripts/vue_shared/components/markdown/suggestions.vue"
"app/assets/javascripts/vue_shared/components/memory_graph.vue"
"app/assets/javascripts/vue_shared/components/project_avatar/image.vue"
"app/assets/javascripts/vue_shared/components/select2_select.vue"
"app/assets/javascripts/vue_shared/components/stacked_progress_bar.vue"
"app/assets/javascripts/vue_shared/components/user_avatar/user_avatar_image.vue")

## now loop through the above array
for i in "${arr[@]}"
do
  echo "Fixing $i"
  yarn fix-i18n-imports "$i"
done