source 'https://rubygems.org'

gem 'pry-byebug', '~> 3.5.1', platform: :mri
gem 'capybara', '~> 2.18.0'
gem 'capybara-screenshot', '~> 1.0.22'
gem 'rake', '~> 12.3.0'
gem 'rspec', '~> 3.7'
gem 'selenium-webdriver', '~> 3.141'
gem 'airborne', '~> 0.2.13'
gem 'addressable', '~> 2.5.2'
gem 'nokogiri', '~> 1.10.3'
gem 'rspec-retry', '~> 0.6.1'
gem 'ffaker', '~> 2.11'
gem 'knapsack', '~> 1.17'
